language: android

jdk:
- oraclejdk8

android:
  components:
  - tools
  licenses:
  - 'android-sdk-license-.+'

before_install:
- chmod +x gradlew
# Install SDK license so Android Gradle plugin can install deps.
- mkdir "$ANDROID_HOME/licenses" || true
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
# Install the rest of tools (e.g., avdmanager)
- sdkmanager tools

install:
- ./gradlew clean assembleRelease --stacktrace

script:
- ./gradlew lintRelease testReleaseUnitTest --stacktrace

branches:
  except:
  - gh-pages

notifications:
  email: false

sudo: false

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache